apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - job.yaml

images:
  - name: 681244251312.dkr.ecr.ap-southeast-3.amazonaws.com/ops-simulator
    newTag: "20260625114424"
