apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 681244251312.dkr.ecr.ap-southeast-3.amazonaws.com/auth-service
    newTag: "20260625113058"
